services:
  - type: web
    name: vayon-erp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --max-requests 1000
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: vayon-erp-db
          property: connectionString
      - key: FLASK_ENV
        value: production
  
  - type: pserv
    name: vayon-erp-db
    env: postgresql
    plan: starter
    ipAllowList: []
